// <auto-generated />
using System;
using HistorialAcademico.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HistorialAcademico.Web.Migrations
{
    [DbContext(typeof(HistorialContext))]
    [Migration("20260929021825_SeccionesOfertadas")]
    partial class SeccionesOfertadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("HistorialAcademico.Core.Entities.ConfiguracionPlanificador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AsumirEnCurso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteAlto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimiteBase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UmbralIndice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionPlanificador");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.ConsultaSecciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<int>("Secciones")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Periodo", "Codigo")
                        .IsUnique();

                    b.ToTable("ConsultasSecciones");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.CursoEnProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasCredito")
                        .HasColumnType("TEXT");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.ToTable("CursosEnProgreso");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.DatosAlumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .HasColumnType("TEXT");

                    b.Property<string>("Escuela")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoAcademico")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradoAObtener")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Programa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAlumno")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHorasAprobadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHorasGanadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHorasIntentadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHorasPga")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPga")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPuntosCalidad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatosAlumno");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.Equivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoBanner")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoPensum")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBanner", "CodigoPensum")
                        .IsUnique();

                    b.ToTable("Equivalencias");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.MateriaCursada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasCredito")
                        .HasColumnType("TEXT");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PuntosCalidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("PeriodoId");

                    b.ToTable("MateriasCursadas");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.MateriaPensum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsElectiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prerrequisitos")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("MateriasPensum");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.MateriaPlanificada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodoPlanificadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Razon")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoPlanificadoId", "Codigo")
                        .IsUnique();

                    b.ToTable("MateriasPlanificadas");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AcumHorasAprobadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcumHorasGanadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcumHorasIntentadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcumHorasPga")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcumPga")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcumPuntosCalidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .HasColumnType("TEXT");

                    b.Property<string>("Escuela")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoAcademico")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasAprobadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasGanadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasIntentadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasPga")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Pga")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PuntosCalidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAlumno")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Orden")
                        .IsUnique();

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.PeriodoPlanificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanEstudioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanEstudioId", "Nombre")
                        .IsUnique();

                    b.ToTable("PeriodosPlanificados");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.PlanEstudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Actualizado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("PlanesEstudio");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.SeccionOfertada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Abierta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloquesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Campus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Consultada")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Creditos")
                        .HasPrecision(4, 1)
                        .HasColumnType("TEXT");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inscritos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nrc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo", "Periodo");

                    b.HasIndex("Periodo", "Nrc")
                        .IsUnique();

                    b.ToTable("SeccionesOfertadas");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.Sincronizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.ToTable("Sincronizaciones");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.MateriaCursada", b =>
                {
                    b.HasOne("HistorialAcademico.Core.Entities.Periodo", "Periodo")
                        .WithMany("Materias")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.MateriaPlanificada", b =>
                {
                    b.HasOne("HistorialAcademico.Core.Entities.PeriodoPlanificado", null)
                        .WithMany("Materias")
                        .HasForeignKey("PeriodoPlanificadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.PeriodoPlanificado", b =>
                {
                    b.HasOne("HistorialAcademico.Core.Entities.PlanEstudio", null)
                        .WithMany("Periodos")
                        .HasForeignKey("PlanEstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.Periodo", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.PeriodoPlanificado", b =>
                {
                    b.Navigation("Materias");
                });

            modelBuilder.Entity("HistorialAcademico.Core.Entities.PlanEstudio", b =>
                {
                    b.Navigation("Periodos");
                });
#pragma warning restore 612, 618
        }
    }
}
